# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 038babe4c7ccbd2d3ee84fdd930d3832971e5066f1662e913c0ca3546689e87d92682bfd7b24e0fd349727093f6a647af051f0492d04ce3af20e03d3b38faee8

test:
  secret_key_base: f7223619178c7337a84f9ee336ad7dbc2c164f4800e953b6b297f7220c824706f87d7b30e72b27081c052cd3c9ac5ba1ddf100fcbaf61ad9079edd70010aa062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
